### PR TITLE
Turn into a Satyrographos package

### PR DESCRIPTION
**Pull request by na4zagin3**
This adds two files: `Satyristes` and `satysfi-lib.opam` so that Satyrographos users can install satysfi-lib with OPAM.

You’ll be able to use for example `random.satyg` as `@require: lib/random`.

### CODE REVIEW

**Comment by nyuichi** [comment]
Thank you for the great pull request!

**Comment by nyuichi** [comment]
@na4zagin3 

BTW do I have to do some extra work when I changed the name of the package to satysfi-base, like sending a pr to your own repository?

**Comment by na4zagin3** [comment]
@nyuichi Thank you for merging this PR!

> BTW do I have to do some extra work when I changed the name of the package to satysfi-base, like sending a pr to your own repository?

I’d be really appreciated if you could send a pr to satyrographos-repo, otherwise I can do on behalf of you.
Anyway, once you publish a new release with `git tag -a`, running `opam publish --repo=na4zagin3/satyrographos-repo` automatically sends a PR to satyrographos-repo.

**Comment by nyuichi** [comment]
> Anyway, once you publish a new release with git tag -a, running opam publish --repo=na4zagin3/satyrographos-repo automatically sends a PR to satyrographos-repo.

That's so cool 😍

**Pull request merged**
